import {
  Controller,
  Get,
  Post,
  UseGuards,
  HttpCode,
  HttpStatus,
  Query,
} from '@nestjs/common';
import {
  ApiTags,
  ApiBearerAuth,
  ApiOperation,
  ApiResponse,
  ApiQuery,
} from '@nestjs/swagger';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { DashboardService } from './dashboard.service';
import { UsersService } from '../users/users.service';

@ApiTags('dashboard')
@Controller()
export class DashboardController {
  constructor(
    private readonly dashboardService: DashboardService,
    private readonly usersService: UsersService,
  ) {}

  // ── Email Verification Endpoint ────────────────────────────────────────────

  @Get('email/verify')
  @ApiOperation({
    summary: 'Verify email address via signed JWT link',
    description:
      'Validates the JWT token in the query string and marks the user email as verified. ' +
      'Links are generated by the mail service and expire in 24 hours.',
  })
  @ApiQuery({ name: 'token', required: true, type: String })
  @ApiResponse({ status: 200, description: 'Email verified successfully' })
  @ApiResponse({ status: 401, description: 'Invalid or expired token' })
  async verifyEmail(@Query('token') token: string) {
    return this.dashboardService.verifyEmailToken(token);
  }

  // ── API Endpoints ──────────────────────────────────────────────────────────

  @Get('api/dashboard/queue')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Get queue statistics (JSON)' })
  async queueStats() {
    return this.dashboardService.getQueueSummary();
  }

  @Get('api/dashboard/users')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Get user statistics (JSON)' })
  async usersStats() {
    let summary = await this.dashboardService.getUsersSummary();
    if (!summary) {
      const raw = await this.usersService.getSummary();
      summary = await this.dashboardService.cacheUsersSummary(raw);
    }
    return summary;
  }

  @Post('api/dashboard/refresh')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Trigger a dashboard refresh via Redis pub/sub',
    description:
      'Publishes a message to the dashboard.summary.refresh channel. ' +
      'All connected WebSocket clients receive updated stats.',
  })
  async refresh() {
    await this.dashboardService.publishRefresh();
    return { message: 'Refresh signal published' };
  }
}
